# Code Owners for ecommerce-web-automated-test-demo
# These owners will be automatically requested for review when someone opens a pull request

# Default owners for everything in the repo
* @subbu-kongani-dev

# Workflow files - require approval from repo owner
/.github/workflows/ @subbu-kongani-dev

# Configuration files - require approval
/pom.xml @subbu-kongani-dev
/src/main/resources/*.properties @subbu-kongani-dev

# Core framework files - require approval
/src/main/java/com/nopcommerce/base/ @subbu-kongani-dev
/src/main/java/com/nopcommerce/utils/ @subbu-kongani-dev
